spring.application.name=intelliShop


# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/intellishopdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
#Configuration du JWT
app.jwt.secret=+1xfpzhS+OLPvC1Q77ZqD55DLUmdriso3/x+TB4wkJU=
app.jwt.expiration-ms=86400000

azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
azure.storage.container-name=produits
azure.storage.public-url=https://intellishopimg.blob.core.windows.net
